<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Laporan Data Layanan</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            margin: 20px;
        }
        .header {
            text-align: center;
            border-bottom: 2px solid #333;
            padding-bottom: 10px;
            margin-bottom: 20px;
        }
        .header h2 {
            margin: 0;
            color: #333;
        }
        .header p {
            margin: 5px 0;
            color: #666;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 15px;
        }
        th {
            background-color: #4e73df;
            color: white;
            padding: 10px 8px;
            text-align: left;
            font-weight: bold;
        }
        td {
            padding: 8px;
            border-bottom: 1px solid #ddd;
        }
        tr:nth-child(even) {
            background-color: #f8f9fc;
        }
        .footer {
            margin-top: 20px;
            text-align: right;
            font-size: 10px;
            color: #666;
            border-top: 1px solid #ddd;
            padding-top: 10px;
        }
        .badge {
            padding: 3px 8px;
            border-radius: 3px;
            font-size: 10px;
            font-weight: bold;
        }
        .badge-pending {
            background-color: #f6c23e;
            color: #333;
        }
        .badge-approved {
            background-color: #1cc88a;
            color: white;
        }
        .badge-rejected {
            background-color: #e74a3b;
            color: white;
        }
        .summary {
            margin-top: 15px;
            padding: 10px;
            background-color: #f8f9fc;
            border-radius: 5px;
        }
    </style>
</head>
<body>
    <div class="header">
        <h2>LAPORAN DATA LAYANAN</h2>
        <p>Periode: {{ \Carbon\Carbon::parse($startDate)->format('d-m-Y') }} s/d {{ \Carbon\Carbon::parse($endDate)->format('d-m-Y') }}</p>
        <p>Total Data: {{ $totalRecords }} record</p>
    </div>

    <div class="summary">
        <strong>Ringkasan:</strong>
        @php
            $totalLayanan = $data->sum('jumlah_layanan');
            $totalKunjungan = $data->sum('jumlah_kunjungan');
        @endphp
        Total Layanan: {{ $totalLayanan }} | Total Kunjungan: {{ $totalKunjungan }}
    </div>

    <table>
        <thead>
            <tr>
                <th>No</th>
                <th>Tanggal</th>
                <th>Petugas</th>
                <th>Instansi</th>
                <th>Layanan</th>
                <th>Jumlah Layanan</th>
                <th>Jumlah Kunjungan</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @foreach($data as $index => $item)
            <tr>
                <td>{{ $index + 1 }}</td>
                <td>{{ \Carbon\Carbon::parse($item['tanggal'])->format('d-m-Y') }}</td>
                <td>{{ $item['petugas'] }}</td>
                <td>{{ $item['instansi'] }}</td>
                <td>{{ $item['layanan'] }}</td>
                <td style="text-align: center;">{{ $item['jumlah_layanan'] }}</td>
                <td style="text-align: center;">{{ $item['jumlah_kunjungan'] }}</td>
                <td>
                    @if($item['status'] == 'pending')
                        <span class="badge badge-pending">Pending</span>
                    @elseif($item['status'] == 'disetujui')
                        <span class="badge badge-approved">Disetujui</span>
                    @elseif($item['status'] == 'ditolak')
                        <span class="badge badge-rejected">Ditolak</span>
                    @else
                        {{ $item['status'] }}
                    @endif
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>Dicetak pada: {{ $generatedAt }}</p>
        <p>Generated by Sistem Informasi Layanan</p>
    </div>
</body>
</html>